### ISSUE TITLE
nosetests fail to run due to missing requirements

### ISSUE THREAD

**Issue by GuyAllard** [varda/varda#35]
The tests require the following python libraries to be installed in addition to those in requirements.txt
- kombu
- billiard

**Comment by martijnvermaat** [comment]
Both are dependencies of Celery, which is in `requirements.txt`:

```
$ pip freeze
virtualenv==13.1.2
$ pip install celery==3.1.9
...
$ pip freeze
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.23
celery==3.1.9
kombu==3.0.35
pytz==2016.6.1
virtualenv==13.1.2
```

**Comment by GuyAllard** [comment]
On an ubuntu box with pip installed using apt-get, kombu and billiard did not get installed as dependencies of celery.

They did install correctly using pip with virtualenv or conda, so I guess that the issue is related to pip version. I'll close this issue as it works fine with virtualenv as described in the instructions.

**Comment by martijnvermaat** [comment]
Ok, that's weird. But :+1:
